version: '3.8'

networks:
  my_network:
    driver: bridge

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_pass.txt

services:
  db:
    image: postgres:12.19-bullseye
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    environment:
      PGDATA: /var/lib/postgresql/new_data
      POSTGRES_DB: db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    expose:
      - "5432"
    networks:
      - my_network

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - my_network

  server:
    restart: always
    build: ./server
    links:
      - db
    secrets:
      - postgres_user
      - postgres_password
    environment:
      DEBUG: False
      POSTGRES_DB: db
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    expose:
      - "8000"
    depends_on:
      - db
    command: >
      sh -c "python3 ./create_db.py && gunicorn -w 2 -b :8000 app:app"
    networks:
      - my_network

volumes:
  db-data:
